### ISSUE TITLE
Use `crates.io` index repo

### ISSUE THREAD

**Issue by ggwpez** [paritytech/parity-publish#11]
Command `status` is running rather slow on the monorepo and seems to do one request per crate?  
Dont know if this was thought about before, but the crates.io index is on [github](https://github.com/rust-lang/crates.io-index/blob/master/sp/-r/sp-runtime).  
So you can get all versions of all crates at once by downloading that repo.

**Comment by Morganamilo** [comment]
Seems reasonable. The index is actually smaller than expected, I thought it would be dozens of GB.

**Comment by ggwpez** [comment]
You can also do a `--depth 1` clone, or rather just access the latest master zip directly without any `.git` overhead:  
https://github.com/rust-lang/crates.io-index/archive/refs/heads/master.zip

**Comment by Morganamilo** [comment]
We'll probably need to pull the newest index on each invocation of this tool so going through git is probably the best way.

**Comment by Morganamilo** [comment]
we use the cargo registry where we can now which is very fast. We still have to use the http api for ownership as that.s a crates.io thing and not a registry thing. That's now dones in parallel so that's not too slow anymore either.
